name: Deploy Laravel ke cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Core Files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          local_path: './*'
          remote_path: '/home/jabarinf/berita_dashboard'
          sftp_only: true
          delete_remote_files: false

      - name: Deploy Public Files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          local_path: './public/*'
          remote_path: '/home/jabarinf/dashboard_jabarinfo.id'
          sftp_only: true
          delete_remote_files: true
